apiVersion: v2
description: FFC Grants file sender microservice
name: ffc-grants-file-sender
# this version is automatically updated in the build pipline
version: 1.0.0
dependencies:
- name: ffc-helm-library
  version: ^2.5.2
  repository: https://raw.githubusercontent.com/defra/ffc-helm-repository/master/
