{{- include "ffc-helm-library.container-secret" (list . "ffc-grants-file-creation.container-secret") -}}
{{- define "ffc-grants-file-creation.container-secret" -}}
stringData:
  APPINSIGHTS_INSTRUMENTATIONKEY: {{ .Values.appInsights.key | quote }}
  BLOB_STORAGE_CONNECTION_STRING: {{ .Values.container.blobStorageConnectionString | quote }}
  SHAREPOINT_CLIENT_ID: {{ .Values.container.sharePointClientId | quote }}
  SHAREPOINT_CLIENT_SECRET: {{ .Values.container.sharePointClientSecret | quote }}
{{- end -}}
